/**
                                                    ,--------.                                                                                                                                                        
                                                    |Runnable|                                                                                                                                                        
                                                    |--------|                                                                                                                                                        
                                                    `--------'                                                                                                                                                        
                                                         |                                                                                                                                                            
                                                         |                                                                                                                                                            
                                ,-------------------------------------------------.                                                                                                                                   
                                |GameLoop                                         |                                                                                                                                   
                                |-------------------------------------------------|                                                                                                                                   
                                |-{static} TARGET_FPS: int                        |                                                                                                                                   
                                |-{static} TARGET_TIME: long                      |                                                                                                                                   
                                |-running: boolean                                |                                                                                                                                   
                                |+GameLoop(manager: GameManager, panel: GamePanel)|                                                                                                                                   
                                |+run(): void                                     |                                                                                                                                   
                                |+stopLoop(): void                                |                                                                                                                                   
                                `-------------------------------------------------'                                                                                                                                   
                                                                                                                                                                                                                      
                                                                                 ,-----------------------------------------------------------------------.                                                            
                                                                                 |Camera                                                                 |                                                            
                                                                                 |-----------------------------------------------------------------------|                                                            
                                                                                 |-{static} MAP_WIDTH: double                                            |                                                            
                                                                                 |-{static} MAP_HEIGHT: double                                           |                                                            
                                                                                 |-playerWorldX: double                                                  |                                                            
                                                                                 |-playerWorldY: double                                                  |                                                            
                                                                                 |-cameraWorldX: double                                                  |                                                            
                                                                                 |-cameraWorldY: double                                                  |                                                            
                                                                                 |-{static} DEAD_ZONE_WIDTH: double                                      |                  ,------.                                  
                                                                                 |-{static} DEAD_ZONE_HEIGHT: double                                     |                  |JFrame|                                  
                                                                                 |-{static} FIXED_RANDER_SIZE: double                                    |                  |------|                                  
                                                                                 |+Camera()                                                              |                  `------'                                  
                                                                                 |+updatePlayerPosition(playerWorldX: double, playerWorldY: double): void|                      |                                     
                                                                                 |+setWindow(window: GameWindow): void                                   |                      |                                     
                                                                                 |+updateCamera(): void                                                  |                      |                                     
                                                                                 |+getCameraSize(): double                                               |                      |                                     
                                                                                 |+getplayerWorldX(): double                                             |                      |                                     
                                                                                 |+getplayerWorldY(): double                                             |                      |                                     
                                                                                 |+getCameraWorldX(): double                                             |                      |                                     
                                                                                 |+getCameraWorldY(): double                                             |                      |                                     
                                                                                 `-----------------------------------------------------------------------'                      |                                     
                                                                                                                                                                                |                                     
                                                                                                                                                                                                                      
                                                                                                                                                   ,--------------------------------------------------------.         
                                                                                                                                                   |GameWindow                                              |         
                                                                                                                                                   |--------------------------------------------------------|         
                                                                                                               ,--------------.         ,------.   |+{static} WIDTH: int                                    |         
                                                                                                               |ActionListener|         |JPanel|   |+{static} HEIGHT: int                                   |         
                                                                                                               |--------------|         |------|   |-cardLayout: CardLayout                                 |         
                                                                                                               `--------------'         `------'   |-mainPanel: JPanel                                      |         
                                                                                                                                                   |+GameWindow(t: TitlePanel, g: GamePanel, o: OptionPanel)|         
                                                                                                                                                   |+changePanel(panelName: String): void                   |         
                                                                                                                                                   |+{static} main(args: String[]): void                    |         
                                                                                                                                                   `--------------------------------------------------------'         
                                                                                                                                                                                                                      
                                                                                                                                                                                  ,----------------------------------.
                                                                                                                                                                                  |TitlePanel                        |
                                                                   ,--------------------------------------------.   ,--------------------------------------.   ,--------------.   |----------------------------------|
                                                                   |CollisionManager                            |   |GamePanel                             |   |OptionPanel   |   |-p: JPanel                        |
                                                                   |--------------------------------------------|   |--------------------------------------|   |--------------|   |~b1: JButton                      |
                                                                   |+CollisionManager()                         |   |-b2: JButton                          |   |-b1: JButton  |   |~b2: JButton                      |
                                                                   |+checkAllCollisions(): void                 |   |+GamePanel()                          |   |-b2: JButton  |   |~b3: JButton                      |
                                                                   |-isColliding(a: Entity, b: Entity): boolean |   |#paintComponent(g: Graphics): void    |   |-b3: JButton  |   |+{static} title: BufferedImage    |
                                                                   |-handleCollision(a: Entity, b: Entity): void|   |+actionPerformed(e: ActionEvent): void|   |+OptionPanel()|   |+loadTitle(): void                |
                                                                   `--------------------------------------------'   `--------------------------------------'   `--------------'   |+TitlePanel()                     |
                                                                                                                                                                                  |#paintComponent(g: Graphics): void|
                                                                                                                                                                                  `----------------------------------'
                                                                                                                                                                                                                      
                           ,------------------------------------------------------------------.                                                                                                                       
                           |GameManager                                                       |                                                                                                                       
                           |------------------------------------------------------------------|                                                                                                                       
                           |-{static} instance: GameManager                                   |                                                                                                                       
                           |-GameManager()                                                    |                                                                                                                       
                           |+{static} getInstance(): GameManager                              |                                                                                                                       
                           |+makePlayer(): void                                               |                                                                                                                       
                           |+removeEntity(E: Entity): void                                    |                                                                                                                       
                           |+makeProjectile(weapon: String, X: int, Y: int, angleT: int): void|                                                                                                                       
                           |+removeProjectile(proj: Projectile): void                         |                                                                                                                       
                           |+getEntity(index: int): Entity                                    |                                                                                                                       
                           |+initialize(): void                                               |                                                                                                                       
                           |+HPhandeler(E: Entity, damage: int): void                         |                                                                                                                       
                           |+updateGame(): void                                               |                                                                                                                       
                           `------------------------------------------------------------------'                                                                                                                       
                                                                                                                                                                                                                      
                                                                                                                                                                                                                      
                                       |                                             ,-------------------------------------------------------------------.                                                            
                                       | ,---------------------------------------.   |Entity                                                             |                                                            
                                       | |MapManager                             |   |-------------------------------------------------------------------|                                                            
                                       | |---------------------------------------|   |+{abstract} getWidth(): int                                        |                                                            
                                       | |+{static} TILE_SIZE: int               |   |+{abstract} getHeight(): int                                       |                                                            
                                       | |+{static} WIDTH_TILES: int             |   |+{abstract} getWorldX(): int                                       |                                                            
                                       | |+{static} HEIGHT_TILES: int            |   |+{abstract} getWorldY(): int                                       |                                                            
                                       | |+{static} MAP_WIDTH: int               |   |+{abstract} getType(): String                                      |                                                            
                                       | |+{static} MAP_HEIGHT: int              |   |+{abstract} getHP(): int                                           |                                                            
                                       | |+{static} floorTileImage: BufferedImage|   |+{abstract} setHP(HP: int): int                                    |                                                            
                                       | |+MapManager()                          |   |+{abstract} getSpeed(): int                                        |                                                            
                                       | |+loadTileset(): void                   |   |+{abstract} setPosition(playerWorldX: int, playerWorldY: int): void|                                                            
                                       | |+getTile(x: int, y: int): char         |   |+{abstract} updatePosition(): void                                 |                                                            
                                       | `---------------------------------------'   |+{abstract} draw(g: Graphics, screenX: int, screenY: int): void    |                                                            
                                       |                                             `-------------------------------------------------------------------'                                                            
                                                                                                                                                                                                                      
                                                                                                                                 ,--------------------------------------------------------. |                         
                                                                                                                                 |Player                                                  | |                         
                                                                                                                                 |--------------------------------------------------------| |                         
                                                                                                                                 |-playerWorldX: double                                   | |                         
                                                                                                                                 |-playerWorldY: double                                   | |                         
                                                                                                                                 |-HP: int                                                | |                         
                                                                                                                                 |+speed: int                                             | |                         
                                                                                                                                 |-angleB: int                                            | |                         
,---------------------------------------------------------.                                                                      |-angleT: int                                            | |                         
|Projectile                                               |                                                                      |-up: boolean                                            | |                         
|---------------------------------------------------------|   ,--------------------------------------------------------.         |-down: boolean                                          | |                         
|-speed: int                                              |   |Wall                                                    |         |-left: boolean                                          | |                         
|-range: int                                              |   |--------------------------------------------------------|         |-right: boolean                                         | |                         
|-WorldX: int                                             |   |-HP: int                                                |         |-Z: boolean                                             | |                         
|-WorldY: int                                             |   |-X: int                                                 |         |-X: boolean                                             | |                         
|-angleT: int                                             |   |-Y: int                                                 |         |-tankBottomImage: BufferedImage                         | |                         
|-damage: int                                             |   |-width: int                                             |         |-tankTopImage: BufferedImage                            | |                         
|-explosionRange: int                                     |   |-height: int                                            |         |-TANK_BOTTOM_WIDTH: int                                 | |                         
|-killingTankIsPossible: boolean                          |   |+Wall(s: String)                                        |         |-TANK_BOTTOM_HEIGHT: int                                | |                         
|-width: int                                              |   |~block(): void                                          |         |-TANK_TOP_WIDTH: int                                    | |                         
|-height: int                                             |   |~broken(): void                                         |         |-TANK_TOP_HEIGHT: int                                   | |                         
|+Projectile(weapon: String, X: int, Y: int, angleT: int) |   |+getWidth(): int                                        |         |-MAP_WIDTH: int                                         | |                         
|+updatePosition(): void                                  |   |+getHeight(): int                                       |         |-MAP_HEIGHT: int                                        | |                         
|+draw(g: Graphics, screenX: int, screenY: int): void     |   |+getWorldX(): int                                       |         |+Player(camera: Camera, mapWidth: int, mapHeight: int)  | |                         
|+drawExplo(g: Graphics, screenX: int, screenY: int): void|   |+getWorldY(): int                                       |         |+getBottomWidth(): int                                  | |                         
|+getWidth(): int                                         |   |+getType(): String                                      |         |+getBottomHeight(): int                                 | |                         
|+getHeight(): int                                        |   |+getHP(): int                                           |         |+getTopHeight(): int                                    | |                         
|+getWorldX(): int                                        |   |+getSpeed(): int                                        |         |+getTopWidth(): int                                     | |                         
|+getWorldY(): int                                        |   |+setPosition(playerWorldX: int, playerWorldY: int): void|         |+getAngleT(): int                                       | |                         
|+getType(): String                                       |   |+setHP(HP: int): int                                    |         |+setPosition(playerWorldX: int, playerWorldY: int): void| |                         
|+getHP(): int                                            |   |+updatePosition(): void                                 |         |+setMoving(keyCode: int, isMoving: boolean): void       | |                         
|+getSpeed(): int                                         |   |+draw(g: Graphics, screenX: int, screenY: int): void    |         |+updatePosition(): void                                 | |                         
|+setPosition(playerWorldX: int, playerWorldY: int): void |   `--------------------------------------------------------'         |+draw(g: Graphics, screenX: int, screenY: int): void    | |                         
|+setHP(HP: int): int                                     |                                                                      |+getWidth(): int                                        | |                         
`---------------------------------------------------------'                                                                      |+getHeight(): int                                       | |                         
                                                                                                                                 |+getWorldX(): int                                       | |                         
                                                                                                                                 |+getWorldY(): int                                       | |                         
                                                                                                                                 |+getType(): String                                      | |                         
                                                                                                                                 |+getHP(): int                                           | |                         
                                                                                                                                 |+getSpeed(): int                                        | |                         
                                                                                                                                 |+setHP(HP: int): int                                    | |                         
                                                                                                                                 `--------------------------------------------------------' |                         
                                                                                                                                                                                                                      
                                                                                                                                                                                                                      
                                                                                                                                 ,--------------------------------------------------------.                           
                                                                                                                                 |TankTop                                                 |                           
                                                                                                                                 |--------------------------------------------------------|                           
                                                                                                                                 |-fireDelay: int                                         |                           
                                                                                                                                 |-angleT: int                                            |                           
                                                                                                                                 |-weapon: String                                         |                           
                                                                                                                                 |-lastFireTime: long                                     |                           
                                                                                                                                 |+fireControl(keyCode: int): void                        |                           
                                                                                                                                 |+fire(): void                                           |                           
                                                                                                                                 |+getWidth(): int                                        |                           
                                                                                                                                 |+getHeight(): int                                       |                           
                                                                                                                                 |+getWorldX(): int                                       |                           
                                                                                                                                 |+getWorldY(): int                                       |                           
                                                                                                                                 |+getType(): String                                      |                           
                                                                                                                                 |+getHP(): int                                           |                           
                                                                                                                                 |+getSpeed(): int                                        |                           
                                                                                                                                 |+setPosition(playerWorldX: int, playerWorldY: int): void|                           
                                                                                                                                 |+setHP(HP: int): int                                    |                           
                                                                                                                                 |+updatePosition(): void                                 |                           
                                                                                                                                 |+draw(g: Graphics, screenX: int, screenY: int): void    |                           
                                                                                                                                 `--------------------------------------------------------'                           

 */
module LocalPVP2PShooting {
	requires java.desktop;
}